Web/DienMay/Areas/Admin/Controllers/LoginController.cs
using System.Web.Mvc;

namespace BanNhaAZ.Areas.Admin.Controllers
{
    public class LoginController : Controller
    {
        // GET: Admin/Login
        public ActionResult Index()
        {
            return View();
        }
    }
}

Web/DienMay/Controllers/LoginController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using BanNhaAZ.Models;
using CommonHelper.Helper;
using Core.Models;

namespace BanNhaAZ.Controllers
{
    public class LoginController : Controller
    {
        private readonly CacheProvider _cacheProvider = new CacheProvider();
        [HttpGet]
        public async Task<ActionResult> Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Index(UserLogin model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            if (!model.UserName.Equals("admin") || !model.Password.Equals("12345aA@!"))
            {
                return View();
            }

            _cacheProvider.Set(Constants.CacheConstant.User, model, 2); //seconds
            return RedirectToAction("Index", "Home", new
            {
                area = "Admin"
            });

            //string apiUrl = "http://" + Request.Url.Host +
            //                (Request.Url.IsDefaultPort ? "" : ":" + Request.Url.Port) + "/token";
            //using (var client = new HttpClient())
            //{
            //    var values = new Dictionary<string, string>
            //    {
            //        { "username", "admin" },
            //        { "password", "12345aA@" },
            //        { "grant_type", "password" },
            //        //{ "username", model.UserName },
            //        //{ "password", model.Password },
            //        //{ "grant_type", "password" },
            //    };

            //    var content = new FormUrlEncodedContent(values);
            //    var response = await client.PostAsync(apiUrl, content);
            //    if (response.IsSuccessStatusCode)
            //    {
            //        var respStr = await response.Content.ReadAsStringAsync();
            //        var fb = JsonConvert.DeserializeObject<UserLoginInformation>(respStr);
            //        _cacheProvider.Set(Constants.CacheConstant.User, fb, 2); //seconds
            //        return RedirectToAction("Index", "Home", new
            //        {
            //            area = "Admin"
            //        });
            //    }
            //    return View();
            //}
        }

        [HttpGet]
        public async Task<ActionResult> LogOut()
        {
            _cacheProvider.Set(Constants.CacheConstant.User, null, 2); //seconds
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<ActionResult> Register()
        {
            return View();
        }
        [HttpGet]
        public async Task<ActionResult> ForgotPassword()
        {
            return View();
        }
    }
}

Web/DienMay/Views/Login/ForgotPassword.cshtml

@{
    ViewBag.Title = "ForgotPassword";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ForgotPassword</h2>


Web/DienMay/Views/Login/Index.cshtml

@{
    ViewBag.Title = "Đăng nhập hệ thống || BanhnhaAz.com";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model BanNhaAZ.Models.UserLogin
<style>
    .validation_message{
        color:red
    }
</style>
<div class="container">
    <h1 class="titH1 bold c_red tit_login"><span id="ucLogin_txtTitle" class="titdn">Đăng nhập</span></h1>
    <hr class="mgb20" />

    <div id="ucLogin_pnlLogin" style="    padding-left: 39%;max-width: 70%;" class="box_login box_ipt_login" ValidationGroup="vldlogin">

        @using (Html.BeginForm("Index",
                                                                           "Login",
                                                                           FormMethod.Post,
                                                                           new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <input name="UserName" type="text" maxlength="50" id="UserName" class="form-control no-radius no-shadow" placeholder="Tên đăng nhập / Email / Điện thoại*" />
            @Html.ValidationMessageFor(t => t.UserName, null, new { @class = "validation_message" })

        </div>
            <div class="form-group">
                <input name="Password" type="password" maxlength="50" id="Password" class="form-control no-radius no-shadow" placeholder="Mật khẩu *" />
                @Html.ValidationMessageFor(t => t.Password, null, new { @class = "validation_message" })

            </div>
            <div class="form-group cbcheck mgb20"><input id="ucLogin_ckbSaver" type="checkbox" name="ucLogin$ckbSaver" /><label for="ucLogin_ckbSaver">  Nhớ mật khẩu</label></div>
            <div class="form-group"><input type="submit" name="ucLogin$btnLogin" value="ĐĂNG NHẬP" id="ucLogin_btnLogin" class="btn bold no-radius" /></div>
        }

        </div>




    <div class="intro clearfix pdt15 mgb20" style="text-align: center;">
        <p><img alt="Quên mật khẩu" src="images/icon/icon-mk.jpg" />&nbsp;&nbsp;<a href="#">Qu&ecirc;n mật khẩu?</a></p>

        <p><img alt="Đăng ký" src="images/icon/icon-dk.jpg" />&nbsp;&nbsp;<a href="#">Đăng k&yacute; th&agrave;nh vi&ecirc;n</a></p>

        <p>Để được trợ gi&uacute;p vui l&ograve;ng li&ecirc;n hệ :</p>

        <p>Hotline <strong><a href="#"><span style="color: #f15b40
">0973.002.5221</span></a></strong> hoặc email <strong><a href="http://mailto:trongnv1507@gmail.com/"><span style="color:#f15b40">trongnv1507@gmail.com</span></a></strong></p>
    </div>
</div>


Web/DienMay/Views/Login/Register.cshtml

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model BanNhaAZ.Models.UserLogin
@section CssPage{
    <link rel='stylesheet' id='ultimate-style-min-css'
          href='~/Content/themes/wp-content/plugins/Ultimate_VC_Addons/assets/min-css/ultimate.min6e85.css?ver=3.13.7' type='text/css'
          media='all' />

    <script type='text/javascript'
            src='~/Content/themes/wp-content/plugins/gravityforms1916/js/jquery.json-1.39915.js?ver=1.9.1.5'></script>
    <script type='text/javascript'
            src='~/Content/themes/wp-content/plugins/gravityforms1916/js/gravityforms.min9915.js?ver=1.9.1.5'></script>
    <script type='text/javascript'
            src='~/Content/themes/wp-content/plugins/gravityforms1916/js/placeholders.jquery.min9915.js?ver=1.9.1.5'></script>
    <style type="text/css" data-type="vc_shortcodes-custom-css">
        .gform_wrapper form {
            text-align: left;
        }

        .validation_message {
            color: #ff5400 !important;
        }

        .gform_body {
            padding-left: 35%;
        }

        .gform_footer.top_label {
            text-align: center;
        }

        #nav {
            text-align: center;
        }
    </style>
}

<div class="container">
    <div id="main-wrapper" class="zozo-row row">
        <div id="single-sidebar-container" class="single-sidebar-container main-col-full">
            <div class="zozo-row row">
                <div id="primary" class="content-area content-col-full">
                    <div id="content" class="site-content">

                        <div id="post-397" class="post-397 page type-page status-publish hentry">
                            <div class="entry-content">
                                <section class="vc_row wpb_row vc_row-fluid vc_custom_1456358816112 vc-zozo-section typo-dark">
                                    <div class="zozo-vc-main-row-inner vc-normal-section">
                                        <div class="container">
                                            <div class="row">
                                                <div class="wpb_column vc_main_column vc_column_container vc_col-sm-12 typo-default">
                                                    <div class="wpb_wrapper">
                                                        <div class="zozo-parallax-header wpb_animate_when_almost_visible wpb_appear">

                                                            <div class="parallax-header"><h4 class="parallax-title text-center">ĐĂNG KÍ TÀI KHOẢN</h4></div>
                                                        </div>
                                                        <div class="wpb_text_column wpb_content_element  wpb_animate_when_almost_visible wpb_appear">
                                                            <div class="wpb_wrapper">

                                                                <div class='gf_browser_unknown gform_wrapper' id='gform_wrapper_8'>
                                                                    <a id='gf_8' name='gf_8' class='gform_anchor'></a>
                                                                    @using (Html.BeginForm("Register",
                                                                        "Login",
                                                                        FormMethod.Post,
                                                                        new { enctype = "multipart/form-data" }))
                                                                    {
                                                                        @Html.AntiForgeryToken()
                                                                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                                                        <div class='gform_heading'>
                                                                            <span class='gform_description'></span>
                                                                        </div>
                                                                        <div class='gform_body'>
                                                                            <ul id='gform_fields_8' class='gform_fields top_label form_sublabel_below description_below'>
                                                                                <li id='field_8_15' class='gfield gfield_contains_required field_sublabel_below field_description_below'>
                                                                                    @Html.LabelFor(s => s.UserName, "Tên đăng nhập", new { @class = "gfield_label" })
                                                                                    <div class="ginput_container">
                                                                                        @Html.TextBoxFor(s => s.UserName, new { @class = "medium" })
                                                                                    </div>
                                                                                    @Html.ValidationMessageFor(t => t.UserName, null, new { @class = "validation_message" })
                                                                                </li>
                                                                                <li id='field_8_5' class='gfield gfield_contains_required field_sublabel_below field_description_below'>
                                                                                    @Html.LabelFor(s => s.Password, "Mật khẩu", new { @class = "gfield_label" })
                                                                                    <div class='ginput_container'> @Html.TextBoxFor(s => s.Password, new { @class = "medium", @tabindex = "3" })</div>
                                                                                    @Html.ValidationMessageFor(t => t.Password, null, new { @class = "validation_message" })
                                                                                </li>
                                                                            </ul>
                                                                        </div>
                                                                        <div class='gform_footer top_label'>
                                                                            <input type='submit' id='gform_submit_button_8' class='gform_button button' value='Đăng nhập' tabindex='9' />
                                                                            <input type='hidden' name='gform_ajax' value='form_id=8&amp;title=&amp;description=1&amp;tabindex=1' />
                                                                            <input type='hidden' class='gform_hidden' name='is_submit_8' value='1' />
                                                                            <input type='hidden' class='gform_hidden' name='gform_submit' value='8' />

                                                                            <input type='hidden' class='gform_hidden' name='gform_unique_id' value='' />
                                                                            <input type='hidden' class='gform_hidden' name='state_8' value='WyJbXSIsIjUyODQyM2Y5MDY1ZDUwMTc5NWIyMjk4NWQ5N2M0NGZhIl0=' />
                                                                            <input type='hidden' class='gform_hidden' name='gform_target_page_number_8' id='gform_target_page_number_8' value='0' />
                                                                            <input type='hidden' class='gform_hidden' name='gform_source_page_number_8' id='gform_source_page_number_8' value='1' />
                                                                            <input type='hidden' name='gform_field_values' value='' />

                                                                        </div>
                                                                    }
                                                                    <p id="nav">
                                                                        <a href="wp-login0ddc.html?action=register">Đăng kí</a> | <a href="dang-nhap-2/lost-password/index.html" title="Tạo mật khẩu mới">Bạn quên mật khẩu?</a>
                                                                    </p>
                                                                </div>
                                                                <iframe style='display:none;width:0px;height:0px;' src='about:blank' name='gform_ajax_frame_8' id='gform_ajax_frame_8'></iframe>
                                                                <script type='text/javascript'>
                                                                </script>
                                                                <script type='text/javascript'>
                                                                    if (typeof gf_global == 'undefined') var gf_global = { "gf_currency_config": { "name": "U.S. Dollar", "symbol_left": "$", "symbol_right": "", "symbol_padding": "", "thousand_separator": ",", "decimal_separator": ".", "decimals": 2 }, "base_url": "http:\/\/giaodichthuanphong.com\/wp-content\/plugins\/gravityforms1916", "number_formats": [], "spinnerUrl": "http:\/\/giaodichthuanphong.com\/wp-content\/plugins\/gravityforms1916\/images\/spinner.gif" }; jQuery(document).bind('gform_post_render', function (event, formId, currentPage) {
                                                                        if (formId == 8) {
                                                                            if (typeof Placeholders != 'undefined') {
                                                                                Placeholders.enable();
                                                                            }
                                                                        }
                                                                    }); jQuery(document).bind('gform_post_conditional_logic', function (event, formId, fields, isInit) { });</script>
                                                                <script type='text/javascript'>jQuery(document).ready(function () { jQuery(document).trigger('gform_post_render', [8, 1]) });</script>

                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </section>



                            </div>
                        </div>
                    </div><!-- #content -->
                </div><!-- #primary -->


            </div>
        </div><!-- #single-sidebar-container -->


    </div><!-- #main-wrapper -->
</div><!-- .container -->